SimpleLogApplication/Models/Ajudante.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;

namespace SimpleLogApplication.Models
{
    public static class Ajudante
    {
        public static string ArquivoLogErros
        {
            get
            {
                return ConfigurationManager.AppSettings[nameof(ArquivoLogErros)];
            }
        }

        public static string ArquivoLogAcoes
        {
            get
            {
                return ConfigurationManager.AppSettings[nameof(ArquivoLogAcoes)];
            }
        }
    }
}

SimpleLogApplication/Models/RegistraLog.cs
using System;
using System.IO;
using System.Web;

namespace SimpleLogApplication.Models
{
    public class RegistraLog
    {
        private static string caminhoAplicacao = string.Empty;

        public static bool Log(string mensagem, string nomeArquivo = "LogGeral")
        {
            try
            {
                RegistraLog.caminhoAplicacao = HttpContext.Current.Server.MapPath("~/App_Data");
                string path = Path.Combine(RegistraLog.caminhoAplicacao, nomeArquivo + ".txt");
                if (!File.Exists(path))
                    File.Create(path).Close();
                using (StreamWriter streamWriter = File.AppendText(path))
                    RegistraLog.AppendLog(mensagem, (TextWriter)streamWriter);
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

        private static void AppendLog(string mensagem, TextWriter writer)
        {
            try
            {
                writer.Write("\r\nLog Entrada: ");
                TextWriter textWriter = writer;
                DateTime now = DateTime.Now;
                string longTimeString = now.ToLongTimeString();
                now = DateTime.Now;
                string longDateString = now.ToLongDateString();
                string str = longTimeString + " " + longDateString;
                textWriter.Write(str);
                writer.WriteLine("");
                writer.WriteLine("Mensagem: " + mensagem + "\n");
                writer.WriteLine("------------------------------------------");
            }
            catch (Exception ex)
            {
            }
        }
    }
}

SimpleLogApplication/Controllers/CalculoController.cs
using SimpleLogApplication.Models;
using System;
using System.Collections.Specialized;
using System.Web.Mvc;

namespace SimpleLog.Controllers
{
    public class CalculoController : Controller
    {
        public ActionResult Index()
        {
            RegistraLog.Log("Abriu a aplicação");
            return (ActionResult)this.View();
        }

        [HttpPost]
        public ActionResult Calcula(string numero1, string numero2)
        {
            try
            {
                NameValueCollection form = Request.Form;
                double num1 = Convert.ToDouble(form[nameof(numero1)]);
                double num2 = Convert.ToDouble(form[nameof(numero2)]);
                double soma = num1 + num2;
                double subtracao = num1 - num2;
                double multiplicacao = num1 * num2;
                double divisao = num1 / num2;
                RegistraLog.Log($"Cálculo executado com sucesso para os números {num1} e {num2}", Ajudante.ArquivoLogAcoes);
                return (ActionResult)this.Json((object)new
                {
                    soma,
                    subtracao,
                    multiplicacao,
                    divisao
                });
            }
            catch (Exception ex)
            {
                RegistraLog.Log(ex.Message + " | StackTrace" + ex.StackTrace, Ajudante.ArquivoLogErros);
                return (ActionResult)this.Json((object)new
                {
                    soma = "-",
                    subtracao = "-",
                    multiplicacao = "-",
                    divisao = "-"
                });
            }
        }

    }
}

SimpleLogApplication/Views/Calculo/Index.cshtml
@{
    ViewBag.Title = "Calcula";
}


<div class="row">
    <div class="col-md-4">
        <h2>Calcular</h2>
        <p>
            @Html.Label("Número 1: ")
            @Html.TextBox("txtNumero1")
        </p>
        <p>
            @Html.Label("Número 2: ")
            @Html.TextBox("txtNumero2")
        </p>
        <p>
            <button id="btnCalcular" class="btn btn-success">Calcular</button>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h3>Resultados</h3>
        <p>Soma: <span id="somaResultado">-</span></p>
        <p>Subtração: <span id="subtracaoResultado">-</span></p>
        <p>Multiplicação: <span id="multiplicacaoResultado">-</span></p>
        <p>Divisão: <span id="divisaoResultado">-</span></p>
    </div>
</div>

@section scripts{
    
<script>

    $("#btnCalcular").on("click", fnCalcular);

    function fnCalcular() {
        var numero1 = $('#txtNumero1').val();
        var numero2 = $('#txtNumero2').val();
      //  alert();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Calcula", "Calculo")',
            dataType: 'json',
            data: { numero1, numero2},
            success: function (data) {
                $('#somaResultado').text(data.soma);
                $('#subtracaoResultado').text(data.subtracao);
                $('#multiplicacaoResultado').text(data.multiplicacao);
                $('#divisaoResultado').text(data.divisao);
            },
            error: function (err) {
                $('#somaResultado').text("-");
                $('#subtracaoResultado').text("-");
                $('#multiplicacaoResultado').text("-");
                $('#divisaoResultado').text("-");
            }
        });
    }

</script>    
    
}

SimpleLogApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
  
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>